schema_version: 1

context:
  version: "1.0.1"

package:
  name: unipatch
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/u/unipatch/unipatch-${{ version }}.tar.gz
  sha256: 876199e2ca3e74fb45afa6fb15caf8a5f076556dbecc3fc4864488bfe3b2b07f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.12.1,<0.13
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - unipatch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Apply unified diffs in memory, compatible with GNU patch.
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/unipatch/

extra:
  recipe-maintainers:
    - thewchan
